apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    helm-app: {{ template "app.name" . }}
    helm-chart: {{ template "app.fullname" . }}
    helm-version: {{ template "app.version" . }}
{{ toYaml .Values.deployment.labels | indent 4 }}
  annotations:
{{ toYaml .Values.annotations | indent 4 }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      helm-app: {{ template "app.name" . }}
      helm-chart: {{ template "app.fullname" . }}
  template:
    metadata:
      labels:
        helm-app: {{ template "app.name" . }}
        helm-chart: {{ template "app.fullname" . }}
    spec:
      {{- if .Values.deployment.initContainers }}
      initContainers:
{{ toYaml .Values.deployment.initContainers | indent 6 }}
      {{- end }}
      {{- if .Values.deployment.strategy }}
{{ toYaml .Values.deployment.strategy }}
      {{- end }}
      imagePullSecrets:
        - name: {{ .Values.deployment.imagePullSecret }}
      {{- if .Values.deployment.affinity }}
      affinity:
{{ toYaml .Values.deployment.affinity | indent 6 }}
      {{- end }}
      {{- if .Values.deployment.tolerations }}
      tolerations:
{{ toYaml .Values.deployment.tolerations | indent 6 }}
      {{- end }}
      containers:
      - name: {{ template "app.fullname" . }}
        image: {{ .Values.deployment.image }}
        imagePullPolicy: {{ .Values.deployment.imagePullPolicy }}
        ports:
        {{- range $key, $value :=  .Values.deployment.ports }}
        - name: {{ $key }}
          port: {{ $value.port }}
          containerPort: {{ $value.containerPort }}
          protocol: {{ $value.protocol }}
        {{- end }}
        env:
          {{- range $key, $value := .Values.deployment.env }}
          - name: "{{ $key }}"
            value: "{{ $value }}"
          {{- end }}
        {{- if .Values.deployment.livenessProbe }}
        livenessProbe:
{{ toYaml .Values.deployment.livenessProbe | indent 10 }}
        {{- end }}
        {{- if .Values.deployment.readinessProbe }}
        readinessProbe:
{{ toYaml .Values.deployment.readinessProbe | indent 10 }}
        {{- end }}
        {{- if .Values.deployment.resources }}
        resources:
{{ toYaml .Values.deployment.resources | indent 10 }}
        {{- end }}
        volumeMounts:
          {{- if .Values.deployment.secrets }}
          - mountPath: {{ .Values.deployment.secrets.mountPath }}
            name: {{ .Values.deployment.secrets.name }}
            readOnly: true
          {{- end }}
      volumes:
        {{- if .Values.deployment.secrets }}
        - name: {{ .Values.deployment.secrets.name }}
          secret:
            secretName: {{ .Values.deployment.secrets.name }}
        {{- end }}



